version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true         # Remove old images after updating
      - WATCHTOWER_INCLUDE_STOPPED=true # Update stopped containers
      - WATCHTOWER_REVIVE_STOPPED=false # Start stopped containers
      #- WATCHTOWER_POLL_INTERVAL=28800  # Check for updates every 5 minutes (300 seconds), 8 hours (28800 seconds)
      - WATCHTOWER_SCHEDULE=0 0 5 * * * # 5am schedule
